# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
auto_detect_solc = false 
bytecode_hash = "none" 
fuzz = { runs = 1_000 } 
libs = ["dependencies"] 
gas_reports = ["*"] 

# Define explicit remappings to match your import statements
remappings = [
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts/contracts/",
  "forge-std/=dependencies/forge-std/src/"
]

[dependencies]
"@openzeppelin-contracts" = { version = "5.0.2" }
"@uniswap-universal-router" = { version = "1.6.0" }
"@prb-math" = { version = "4.0.2" }
forge-std = { version = "1.8.1" }